
services:
  app:
    volumes:
      - ./output:/app/output
    build:
      context: .
      dockerfile: app/Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: app/Dockerfile.bot
    env_file: .env
    depends_on:
      - app
